// Generated by drizzle-kit introspect against production Postgres.
// Source of truth lives in ../../drizzle/schema.ts — this file just re-exports
// so application code can import from @/db/schema and stay decoupled from
// Drizzle's introspection output path.
export * from "../../drizzle/schema";
export * from "../../drizzle/relations";
